sudo: false
os:
  - osx
language: cpp

script:
  - export CXXFLAGS="--std=c++11 -O3 -Wall -Wextra -isystem /usr/local/include"
  - export LIBS="-L/usr/local/lib -lboost_iostreams -lbz2 -lcryptopp -lpthread -lpng -lz"
  - make CXXFLAGS="$CXXFLAGS" LIBS="$LIBS" && make CXXFLAGS="$CXXFLAGS" LIBS="$LIBS" test

before_install:
  - brew update
  - if [[ -z $(brew ls --versions lbzip2) ]]; then brew install lbzip2; fi
  - brew outdated lbzip2 || brew upgrade lbzip2
  - if [[ -z $(brew ls --versions lzlib) ]]; then brew install lzlib; fi
  - brew outdated lzlib || brew upgrade lzlib
  - if [[ -z $(brew ls --versions libpng) ]]; then brew install libpng; fi
  - brew outdated libpng || brew upgrade libpng
  - if [[ -z $(brew ls --versions cryptopp) ]]; then brew install cryptopp; fi
  - brew outdated cryptopp || brew upgrade cryptopp
  - if [[ -z $(brew ls --versions boost) ]]; then brew install boost; fi
  - brew outdated boost || brew upgrade boost

notifications:
  email: false